### ISSUE TITLE
Publish gochain-icon in docker hub

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/gochain-local#1]
Is it possible to get gochain-icon image in docker hub so that developers would not need to build image in their machine locally with each new version of goloop?
https://github.com/icon-project/gochain-local/blob/04ceab804da33799374aaea16a503afa22ec265f/run_gochain.sh#L25

**Comment by sink772** [comment]
Hello @ajaya-man, as you know, `gochain-icon` image is not for production purpose, but just for development purpose.
I think any developer who wants to use `gochain-icon` image should be able to build the image, because you may need to modify parts of the engine code to debug your Dapps' code behavior.
Also, I don't want to burden myself with posting images to docker hub whenever a new version of goloop is released.
