### ISSUE TITLE
goloop/gochain-icon not on docker hub

### ISSUE THREAD

**Issue by paulrouge** [icon-project/gochain-local#4]
It seems that the goloop/gochain-icon repo is not on docker hub (anymore). Trying to find a image that works with the start scripts but having some issues getting the gochain running.

**Comment by sink772** [comment]
It's a duplicate as #1.

I personally do not think it's necessary because the `goloop/gochain-image` can be very easily created by one line make command as I described in README file.
```
make gochain-icon-image
```
The only thing required is the patience to wait for the build to finish.

Nevertheless, you still think it's necessary to pull a prebuilt image from the docker hub, you may consider using `iconloop/goloop-icon` image which is managed by ICONLOOP infra team.  The following is the example of how to use it.
https://github.com/icon-project/btp/blob/iconloop-v2/e2edemo/docker/docker-compose.yml

**Comment by OccultSlolem** [comment]
The "convenience" build script fails 100% of the time because it's not on Docker Hub. The docs also near unanimously say to pull the image from there. Either the docs and script need to be urgently updated, or the image should be put on Hub.

**Comment by sink772** [comment]
Closed as no feedback from @paulrouge
